### ISSUE TITLE
Error: WDP Packaged Plugin: One or more capabilities not found

### ISSUE THREAD

**Issue by moolwalk** [Scottj1s/PackagedPluginDemo#1]
Hello,

I've recently started to study Windows Device Portal inspired by the Scott's MSDN article and tried to build and run this sample project. But I've got the error and can't get it to work. Could you help me to figure out the cause of the issue?

 - OS : Windows 10 1809(RS5)
 - SDK : Windows 10 1809 Build 17763.1

I also tried to target the build to Windows 10 1803 Build 17134 but it didn't work either.
I've captured the verbose log message from WebManagement.exe as below.

Thank you in advance,
Jesse Ahn

---------------------------------------------------------------------------------------------------------
WDP Packaged Plugin: Found capability: S-1-15-3-3
WDP Packaged Plugin: Found capability: S-1-15-3-1024-676841816-1149237631-4032147681-1035363705-1749014660-2240504816-969164111-1508678073
WDP Packaged Plugin: Found capability: S-1-15-3-1024-2579371802-50273823-2532007077-778130756-637227457-1650229637-1599285538-2684141260
WDP Packaged Plugin: Found capability: S-1-15-3-1024-2732930991-1716039000-1394599507-3926803129-3068501044-2027633224-866606239-446136062
WDP Packaged Plugin: Found capability: S-1-15-3-4010579262-1502888002-2217721724-3880011660-1935275379-779138690-1505917132
**WDP Packaged Plugin: One or more capabilities not found**
WDP Packaged Plugin: Registered:
        DisplayName: MyPluginApp
        AppServiceName: com.contoso.www.myapp
        PackageFamilyName: MyPackagedPlugin_36smgs5sb58xr
        ContentRoute: /myapp/www/
        ContentPath: D:\views\UWPSrc\MyPackagedPlugin\MyPackagedPlugin\bin\x64\Release\AppX\myapp\www\
        HandlerRoute: /myapp/API/
        **HasCaps: False**
WDP Packaged Plugin: Found capability: S-1-15-3-3
WDP Packaged Plugin: Found capability: S-1-15-3-1024-676841816-1149237631-4032147681-1035363705-1749014660-2240504816-969164111-1508678073
WDP Packaged Plugin: Found capability: S-1-15-3-1024-2579371802-50273823-2532007077-778130756-637227457-1650229637-1599285538-2684141260
WDP Packaged Plugin: Found capability: S-1-15-3-1024-2732930991-1716039000-1394599507-3926803129-3068501044-2027633224-866606239-446136062
WDP Packaged Plugin: Found capability: S-1-15-3-4010579262-1502888002-2217721724-3880011660-1935275379-779138690-1505917132
**WDP Packaged Plugin: One or more capabilities not found**
WDP Packaged Plugin: Registered:
        DisplayName: MyPluginComponent
        AppServiceName: com.contoso.www.mycomponent
        PackageFamilyName: MyPackagedPlugin_36smgs5sb58xr
        ContentRoute:
        ContentPath:
        HandlerRoute: /mycomponent/API/
        **HasCaps: False**
...

**Comment by Scottj1s** [comment]
Hello Jesse, 

Thanks for alerting me to this.  Yes, Windows 10 1809 (RS5) included a change that requires an update to WDP packaged plugins.  A third capability is now required, **internetClientServer**.  Please add that to your manifest and the plugin should execute.

- Scott

**Comment by moolwalk** [comment]
Hello Scott,
I've verified that it works in Windows 10 1809 after adding internetClientServer capability in the project.
Thanks,
Jesse
